In [12]:
# My Utility : auxiliars functions

import pandas as pd
import numpy  as np
  

# Initialize weights
def iniWs():    
    ...
    return()

# Initialize weights for one-layer    
def iniW(next,prev):
    r = np.sqrt(6/(next+ prev))
    w = np.random.rand(next,prev)
    w = w*2*r-r    
    return(w)

# Feed-forward of SNN
def forward():
    ...    
    return() 

#Activation function
def act_function(nodo):
    return(np.maximum(0, nodo))
# Derivate of the activation funciton
def deriva_act(nodo):
    return (nodo > 0).astype(float)

#Feed-Backward of SNN
def gradW():    
    ...    
    return()    

# Update Ws
def updW():
    ...    
    return(...)

# Measure
def metricas(x,y):
    ...    
    return()
    
#Confusion matrix
def confusion_matrix(z,y):
    ...    
    return(cm)
#-----------------------------------------------------------------------

In [4]:
import pandas as pd
import numpy as np
def act_function(nodo):
    return(np.maximum(0, nodo))  

def deriva_act(nodo):
    return (nodo > 0).astype(float)

In [10]:
data = pd.read_csv('Data_1.csv', header = None)
xe = data.iloc[:,:-1]
xe = np.array(xe)
ye = data.iloc[:, -1]
ye = pd.get_dummies(ye)
ye = np.array(ye)
ye = ye.T



In [11]:
print (xe)

[[ 5.3197e-02  8.8662e-02  9.9718e-02 ...  7.3850e-02  9.4920e-02
   9.6172e-02]
 [ 4.6104e-02 -3.7134e-02 -8.9496e-02 ... -8.9705e-03  1.8150e-02
   2.6703e-02]
 [ 6.4254e-02  6.3002e-02 -4.3809e-03 ...  1.3560e-02  1.7732e-02
   3.1084e-02]
 ...
 [-2.5990e-02 -2.7208e-02 -4.7918e-02 ... -1.7340e+00 -4.9989e-01
   2.8284e+00]
 [-8.7715e-02 -2.0304e-03  9.2994e-02 ... -7.5695e-01  1.2479e+00
  -3.6792e-01]
 [-2.7614e-01  6.2538e-02  4.1827e-02 ... -9.3400e-03 -4.0609e-04
   5.5228e-02]]


In [13]:
ye = data.iloc[:, -1]
ye = pd.get_dummies(ye)
ye = np.array(ye)
ye = ye.T
print (ye)

[[1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1]]


In [ ]:
import pandas     as pd
import numpy      as np
import math
from numpy.linalg import norm

def entropy_spectral(X):
  H = 0
  A = saca_a(X)

  for i in range(len(X)):
    p = p(A,i)
    H+= p*np.log2(p)

  H = (-1/np.log2(len(X))) * H
  return H

def saca_a(X):
  A = np.zeros(X.shape)

  for i in range(X.shape):
    Ak = 0
    Ak = np.sum(X*np.exp(-2j*math.pi*(i*np.arange(X.shape/X.shape))))

    Ak = norm(Ak)
    A[i] = Ak
  return A

  